Event_Tracker-main/django-schools-master/django_school/classroom/urls.py
from django.urls import include, path
from django.conf.urls import url
from .views import classroom, students, organizers

urlpatterns = [
    # url(r"^save_state/$", classroom.save_state, name="save_state"),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("", classroom.home, name="home"),
    path(
        "students/",
        include(
            (
                [
                    path("event/", students.EventListView.as_view(), name="event_list"),
                    # path("s/", students.StudentList.as_view(), name="student_list"),
                    # path(
                    #     "interests/",
                    #     students.StudentInterestsView.as_view(),
                    #     name="student_interests",
                    # ),
                    # path(
                    #     "event/<int:pk>/",
                    #     students.EventDetailView.as_view(),
                    #     name="event-detail",
                    # ),
                    path(
                        "enrolled/",
                        students.EnrolledEventListView.as_view(),
                        name="enrolled_event_list",
                    ),
                    path("enroll/<int:pk>", students.enroll_event, name="enroll_event"),
                    path("event/<int:pk>/", students.event_detail, name="event-detail"),
                    path(
                        "enrolledevent/<int:pk>/",
                        students.enrolled_event_detail,
                        name="enrolled_event_detail",
                    ),
                    path(
                        "enrolledevent/<int:pk>/download",
                        students.download_certi,
                        name="certi",
                    ),
                    path(
                        "enrolledevent/<int:pk>/feedback",
                        students.feedback_form,
                        name="feedback_form",
                    ),
                    path(
                        "enrolledevent/<int:pk>/feedback/save",
                        students.student_feedback,
                        name="feedback",
                    )
                    # path(
                    #     "event/<int:pk>/studentresults/",
                    #     students.EventResultsView.as_view(),
                    #     name="student_event_results",
                    # ),
                ],
                "classroom",
            ),
            namespace="students",
        ),
    ),
    path(
        "organizers/",
        include(
            (
                [
                    path(
                        "", organizers.EventListView.as_view(), name="event_change_list"
                    ),
                    path(
                        "updatedetails/",
                        organizers.DetailsCreateView.as_view(),
                        name="update_details",
                    ),
                    path(
                        "event/add/",
                        organizers.EventCreateView.as_view(),
                        name="event_add",
                    ),
                    path(
                        "event/<int:pk>/",
                        organizers.EventUpdateView.as_view(),
                        name="event_change",
                    ),
                    path(
                        "event/<int:pk>/results/",
                        organizers.EventResultsView.as_view(),
                        name="event_results",
                    ),
                    path(
                        "event/<int:pk>/results/attendance",
                        organizers.EventAttendanceView.as_view(),
                        name="event_attendance",
                    ),
                    path(
                        "event/<int:pk>/results/attendees/",
                        organizers.AttendeesView.as_view(),
                        name="event_attendees",
                    ),
                    path(
                        "event/<int:pk>/results/gen_certi",
                        organizers.generate_certificate,
                        name="generate",
                    ),
                    path(
                        "event/<int:pk>/results/absent_mail",
                        organizers.absent_mail,
                        name="absent_mail",
                    ),
                    # path("savedata/", organizers.savedata, name="save",),
                    path("savedata/<int:pk>", organizers.save_data, name="savedata",),
                    # path(
                    #     "quiz/<int:quiz_pk>/question/<int:question_pk>/",
                    #     teachers.question_change,
                    #     name="question_change",
                    # ),
                    # path(
                    #     "quiz/<int:quiz_pk>/question/<int:question_pk>/delete/",
                    #     teachers.QuestionDeleteView.as_view(),
                    #     name="question_delete",
                    # ),
                ],
                "classroom",
            ),
            namespace="organizers",
        ),
    ),
]

Event_Tracker-main/django-schools-master/django_school/django_school/urls.py
from django.urls import include, path
from django.contrib import admin
from classroom.views import classroom, students, organizers
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("classroom.urls")),
    # path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/signup/", classroom.SignUpView.as_view(), name="signup"),
    path(
        "accounts/signup/student/",
        students.StudentSignUpView.as_view(),
        name="student_signup",
    ),
    path(
        "accounts/signup/organizer/",
        organizers.OrganizerSignUpView.as_view(),
        name="organizer_signup",
    ),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Event_Tracker-main/django-schools-master/django_school/classroom/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from ..decorators import organizer_required
from django.contrib.auth.decorators import login_required


class SignUpView(TemplateView):
    template_name = "registration/signup.html"


def home(request):
    if request.user.is_authenticated:
        if request.user.is_organizer:
            return redirect("organizers:event_change_list")
        elif request.user.is_student:
            return redirect("students:event_list")
        else:
            return redirect("admin:index")
    return render(request, "classroom/home.html")


# @login_required
# @organizer_required
# def save_state(request):
#     if request.method == "POST":
#         title = request.POST.get("student_name", "")
#         checked = request.POST.get("checked", "")
#         print(title)
#         print(checked)
#         # todo = Todo.objects.get(title=title)
#         # todo.completed = checked
#         # todo.save()

Event_Tracker-main/django-schools-master/django_school/classroom/views/organizers.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from PIL import Image, ImageDraw, ImageFont
import os
import io
from django.conf import settings
from django.utils.encoding import smart_str

from django.core.mail import EmailMessage

from django.db import transaction
from django.db.models import Avg, Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render, HttpResponse
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from django.templatetags.static import static
from bootstrap_datepicker_plus import DateTimePickerInput

from ..decorators import organizer_required
from ..forms import (
    OrganizerSignUpForm,
    EventForm,
)
from ..models import Event, Organizer, EnrolledEvents


User = get_user_model()


class OrganizerSignUpView(CreateView):
    model = User
    form_class = OrganizerSignUpForm
    template_name = "registration/signup_form.html"

    def get_context_data(self, **kwargs):
        kwargs["user_type"] = "organizer"
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        messages.success(
            self.request,
            "The account was created Successfully!Please Update your Informtion to get started!",
        )
        return redirect("organizers:update_details")


@method_decorator([login_required, organizer_required], name="dispatch")
class EventListView(ListView):
    model = Event
    ordering = ("name",)
    context_object_name = "events"
    template_name = "classroom/organizers/event_change_list.html"

    def get_queryset(self):
        queryset = self.request.user.events.select_related("organizer")
        return queryset


@method_decorator([login_required, organizer_required], name="dispatch")
class EventCreateView(generic.edit.CreateView):
    model = Event
    form_class = EventForm
    template_name = "classroom/organizers/event_add_form.html"

    def form_valid(self, form):
        event = form.save(commit=False)
        event.owner = self.request.user
        event.save()
        messages.success(self.request, "The event was created with success!Go Ahead!")
        return redirect("organizers:event_change", event.pk)


@method_decorator([login_required, organizer_required], name="dispatch")
class DetailsCreateView(CreateView):
    model = Organizer
    fields = (
        "name",
        "description",
        "email",
        "contact",
        "color",
    )
    template_name = "classroom/organizers/update_details_form.html"

    def form_valid(self, form):
        organizer = form.save(commit=False)
        organizer.save()
        messages.success(self.request, "The Details are Updated Successfully!Go Ahead!")
        return redirect("organizers:event_change_list")


@method_decorator([login_required, organizer_required], name="dispatch")
class EventUpdateView(UpdateView):
    model = Event
    form_class = EventForm
    context_object_name = "event"
    template_name = "classroom/organizers/event_change_form.html"

    def get_context_data(self, **kwargs):
        kwargs["questions"] = self.get_object().questions.annotate(
            answers_count=Count("answers")
        )
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.events.all()

    def get_success_url(self):
        return reverse("organizers:event_change", kwargs={"pk": self.object.pk})


@method_decorator([login_required, organizer_required], name="dispatch")
class EventResultsView(DetailView):
    model = Event
    context_object_name = "event"
    template_name = "classroom/organizers/event_results.html"

    def get_context_data(self, **kwargs):
        event = self.get_object()
        enrolled_students = event.enrolled_events.select_related(
            "student__user"
        ).order_by("-date")
        total_enrolled_students = enrolled_students.count()
        extra_context = {
            "enrolled_students": enrolled_students,
            "total_enrolled_students": total_enrolled_students,
        }
        kwargs.update(extra_context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.events.all()


@method_decorator([login_required, organizer_required], name="dispatch")
class EventAttendanceView(DetailView):
    model = Event
    context_object_name = "event"
    template_name = "classroom/organizers/event_attendance.html"

    def get_context_data(self, **kwargs):
        event = self.get_object()
        enrolled_students = event.enrolled_events.select_related(
            "student__user"
        ).order_by("-date")
        total_enrolled_students = enrolled_students.count()
        extra_context = {
            "enrolled_students": enrolled_students,
            "total_enrolled_students": total_enrolled_students,
        }
        kwargs.update(extra_context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.events.all()


@login_required
@organizer_required
def save_data(request, pk):
    if request.method == "POST":
        # print(request.POST.getlist("present"))
        student_list = request.POST.getlist("present")
        event = Event.objects.get(pk=pk)
        # print(event)

        EnrolledEvents.objects.filter(event=event).filter(
            student__in=student_list
        ).update(present=True)

        EnrolledEvents.objects.filter(event=event).exclude(
            student__in=student_list
        ).update(present=False)
        messages.success(request, "Attendance was Updated Successfully! Go Ahead!")
        return redirect("organizers:event_change_list")


@method_decorator([login_required, organizer_required], name="dispatch")
class AttendeesView(DetailView):
    model = Event
    context_object_name = "event"
    template_name = "classroom/organizers/attendees.html"

    def get_context_data(self, **kwargs):
        event = self.get_object()
        enrolled_students = event.enrolled_events.select_related(
            "student__user"
        ).order_by("-date")
        student_p = EnrolledEvents.objects.filter(event=event, present=True)
        student_a = EnrolledEvents.objects.filter(event=event, present=False)
        attendees_count = student_p.count()
        absentees_count = student_a.count()
        extra_context = {
            "presentees": student_p,
            "absentees": student_a,
            "attendees_count": attendees_count,
            "absentees_count": absentees_count,
        }
        kwargs.update(extra_context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.events.all()


@login_required
@organizer_required
def generate_certificate(request, pk):
    event = Event.objects.get(pk=pk)
    if request.method == "POST":
        enrolled_students = event.enrolled_events.select_related(
            "student__user"
        ).filter(present=True)
        img_url = os.path.join(settings.MEDIA_ROOT, "certi_template.jpg")
        font_path = os.path.join(
            os.path.join(settings.BASE_DIR, "static"), "fonts/Pacifico.ttf"
        )
        font_path1 = os.path.join(
            os.path.join(settings.BASE_DIR, "static"), "fonts/Alexandroupoli.ttf"
        )
        for s in enrolled_students:
            name = s.student.user.first_name + " " + s.student.user.last_name
            text_y_position1 = 550
            text_y_position2 = 780
            text_y_position3 = 950
            img = Image.open(img_url, mode="r")
            image_width = img.width
            image_height = img.height
            draw = ImageDraw.Draw(img)
            date = str(event.dateofEvent)
            font1 = ImageFont.truetype(font_path, 100)
            font2 = ImageFont.truetype(font_path, 70)
            font3 = ImageFont.truetype(font_path, 60)
            font4 = ImageFont.truetype(font_path1, 60)
            text_width1, _ = draw.textsize(name, font=font1)
            text_width2, _ = draw.textsize(event.name, font=font2)
            draw.text(
                ((image_width - text_width1) / 2, text_y_position1,),
                name,
                font=font1,
                fill=(96, 96, 96),
            )
            draw.text(
                ((image_width - text_width2) / 2, text_y_position2,),
                event.name,
                font=font2,
                fill=(96, 96, 96),
            )
            draw.text(
                (1200, text_y_position3,), date, font=font3, fill=(96, 96, 96),
            )
            draw.text(
                (570, text_y_position3,), "Vnrvjiet", font=font4, fill=(96, 96, 96),
            )
            # img.show()
            file_path = os.path.join(settings.MEDIA_ROOT, "gmail_certi/certificate.jpg")
            img.save(file_path)
            student_instance = EnrolledEvents.objects.filter(event=event).filter(
                student=s.student
            )
            student_instance.update(certificate=img.tobytes())
            subject = "Certificate of " + event.name + " from Terrific Trio!"
            message = "Congratulations!!! You have succesfully achieved Certificate from Terrific Trio.Please download it from the website!"
            recepient = s.student.user.email
            msg = EmailMessage(subject, message, settings.EMAIL_HOST_USER, [recepient])
            msg.content_subtype = "html"
            msg.attach_file(file_path)
            msg.send()

        return redirect("organizers:event_change_list")


@login_required
@organizer_required

Event_Tracker-main/django-schools-master/django_school/classroom/templates/classroom/organizers/attendees.html
{% extends 'base.html' %}

{% load crispy_forms_tags humanize %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'organizers:event_change_list' %}">My Events</a></li>
      <li class="breadcrumb-item"><a href="{% url 'organizers:event_change' event.pk %}">{{ event.name }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'organizers:event_results' event.pk %}">Participants</a></li>
      <li class="breadcrumb-item active" aria-current="page">Attendees Forum</li>
    </ol>
  </nav>
  <div class="container">
  <div class="row">
    <div class="col-6">
      <h2 class="mb-3">{{ event.name }} Participants</h2>
    </div>
    {% comment %} <div class="col-3">
      <a href="{% url 'organizers:event_attendance' event.pk %}" class="btn btn-success">Mark Attendance</a>
    </div> {% endcomment %}
    
  </div>
  <div class="card">
    <div class="card-header">
      <strong>Attended Students</strong>
      <span class="badge badge-pill badge-dark float-right">Total Attendees: {{ attendees_count|default_if_none:0 }}</span>
      <span class = "float-center">
        <form method = "POST" action = "{% url 'organizers:generate' event.pk%}">
              {% csrf_token %}
              <button type = "submit" value = "Submit" class = "btn btn-info"> Issue Certificate</button>
        </form>
      </span>
    </div>
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Username</th>
          <th>Student</th>
        </tr>
      </thead>
      <tbody>
        {% for present in presentees %}
          <tr>
            <td>{{ present.student.user.username }}</td>
            <td>{{ present.student.user.first_name }}&nbsp{{present.student.user.last_name}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="card-footer text-muted">
      <p class="text-success">***Eligible to recieve certificate</p>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <strong>Absentees</strong>
      <span class="badge badge-pill badge-dark float-right">Total Absentees: {{ absentees_count|default_if_none:0 }}</span>
      <span class = "float-center">
        <form method = "POST" action = "{% url 'organizers:absent_mail' event.pk%}">
              {% csrf_token %}
              <button type = "submit" value = "Submit" class = "btn btn-info"> Mail-Absentees</button>
        </form>
      </span>
    </div>
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Username</th>
          <th>Student</th>
        </tr>
      </thead>
      <tbody>
        {% for absent in absentees %}
          <tr>
            <td>{{ absent.student.user.username }}</td>
            <td>{{ absent.student.user.first_name }}&nbsp{{absent.student.user.last_name}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="card-footer text-muted">
      <p class="text-danger">***Not-Eligible to recieve certificate</p>
    </div>
  </div>
{% endblock %}

Event_Tracker-main/django-schools-master/django_school/classroom/templates/classroom/organizers/event_attendance.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}VNR COLORS{% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/fontello-2f186091/css/fontello.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'datatables/dataTables.bootstrap4.min.css' %}">

    {% if user.is_authenticated and user.is_organizer %}
      <style>
        body {
          background-color: #b0aac2;
        }
      </style>
    {% else %}
      <style>
        body {
          background-color: #c2d4d8;
        }
    </style>
    {% endif %}
    <style>
      /* Toggle Button */
      .cm-toggle {
        -webkit-appearance: none;
        -webkit-tap-highlight-color: transparent;
        position: relative;
        border: 0;
        outline: 0;
        cursor: pointer;
        margin: 10px;
      }
      /* To create surface of toggle button */
      .cm-toggle:after {
        content: '';
        width: 60px;
        height: 28px;
        display: inline-block;
        background: rgba(196, 195, 195, 0.55);
        border-radius: 18px;
        clear: both;
      }


      /* Contents before checkbox to create toggle handle */
      .cm-toggle:before {
        content: '';
        width: 32px;
        height: 32px;
        display: block;
        position: absolute;
        left: 0;
        top: -3px;
        border-radius: 50%;
        background: rgb(255, 255, 255);
        box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.6);
      }


      /* Shift the handle to left on check event */
      .cm-toggle:checked:before {
        left: 32px;
        box-shadow: -1px 1px 3px rgba(0, 0, 0, 0.6);
      }
      /* Background color when toggle button will be active */
      .cm-toggle:checked:after {
        background: #3CDE14;
      }
      /* Transition for smoothness */
        .cm-toggle,
        .cm-toggle:before,
        .cm-toggle:after,
        .cm-toggle:checked:before,
        .cm-toggle:checked:after {
          transition: ease .3s;
          -webkit-transition: ease .3s;
          -moz-transition: ease .3s;
          -o-transition: ease .3s;
        }
    </style>
  </head>
  <body>
    <div class="container my-4" background = "">
      <div class="row justify-content-center">
        <div class="col-md-10 col-sm-12">
          <div class="row">
            <div class="col-6">
              <h1 class="logo" >
                <a href="{% url 'home' %}">
                  VNR COLORS
                  {% if user.is_authenticated %}
                    {% if user.is_organizer %}
                      <span class="icon-feather" data-toggle="tooltip" data-placement="right" title="Organizer profile"></span>

                    {% else %}
                      <span class="icon-graduation-cap" data-toggle="tooltip" data-placement="right" title="Student profile"></span>
                    {% endif %}
                  {% endif %}
                </a>
              </h1>
            </div>
            <div class="col-6 text-right">
              {% if user.is_authenticated %}
                <p class="pt-3"><strong>{{ user.username }}{% if user.is_student %} {% endif %}</strong> | <a href="{% url 'logout' %}">Log out</a>.</p>
              {% else %}
                <a href="{% url 'login' %}" class="btn btn-light" role="button">Log in</a>
                <a href="{% url 'signup' %}" class="btn btn-primary" role="button">Sign up</a>
              {% endif %}
            </div>
          </div>
          <div class="card mb-3">
            <div class="card-body">
              {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                </div>
              {% endfor %}

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'organizers:event_change_list' %}">My Events</a></li>
      <li class="breadcrumb-item"><a href="{% url 'organizers:event_change' event.pk %}">{{ event.name }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'organizers:event_results' event.pk %}">Participants</a></li>
      <li class="breadcrumb-item active" aria-current="page">Attendance Forum</li>
    </ol>
  </nav>
  <div class="container">
  <div class="row">
    <div class="col">
      <h2 class="mb-3">{{ event.name }} Attendance</h2>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <strong>Enrolled Students</strong>
      <span class="badge badge-pill badge-primary float-right">Total Participants: {{ total_enrolled_students|default_if_none:0 }}</span>
    </div>
    <table class="table table-bordered mb-0" id="tb_eventlist">
      <thead>
        <tr>
          <th>Username</th>
          <th>Student</th>
          <th>Attendance</th>
          {% comment %} <th>Percentage</th> {% endcomment %}
        </tr>
      </thead>
      <tbody>
      <form method = "POST" action = "{% url 'organizers:savedata' event.pk%}">
        {% csrf_token %}
        {% for enrolled_student in enrolled_students %}
          <tr>
            <td>{{ enrolled_student.student.user.username }}</td>
            <td>{{ enrolled_student.student.user.first_name }}&nbsp{{enrolled_student.student.user.last_name}}</td>
            <td><input type="checkbox" name = "present" value = "{{enrolled_student.student.user.id}}"
                        {% if enrolled_student.present is True %} checked {% endif %} 
                        class = "cm-toggle">
                        </td>
          </tr>
        {% endfor %}
       </tbody>
    </table>
    <div class="card-footer text-muted">
      Total Participants: <strong>{{ total_enrolled_students }}</strong>
      <tr><button type = "submit" value = "Submit" class = "btn btn-primary mr-0"> Submit</button></tr>

    </div>
    </form>

  </div>
</div>
</div>
</div>
      </div>
    </div>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript">
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      });
    </script>
      </body>
</html>

Event_Tracker-main/django-schools-master/django_school/classroom/templates/classroom/organizers/event_change_list.html
{% extends 'base.html' %} {% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">My Jobs</li>
  </ol>
</nav>
<div class="row">
  <div class="col-6">
    <h2 class="mb-3">My Jobs</h2>
  </div>
</div>
<a
  href="{% url 'organizers:event_add' %}"
  class="btn btn-primary mb-3"
  role="button"
  >Add Job</a
>
<div class="card">
  <table class="table mb-0">
    <thead>
      <tr>
        <th>Job</th>
        {% comment %}
        <th>Organizer</th>
        {% endcomment %}
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for event in events %}
      <tr>
        <td class="align-middle">
          <a href="{% url 'organizers:event_change' event.pk %}"
            >{{ event.name }}</a
          >
        </td>
        {% comment %}
        <td class="align-middle">{{ event.organizer }}</td>
        {% endcomment %} {% comment %}
        <td class="align-middle">{{ quiz.questions_count }}</td>
        <td class="align-middle">{{ quiz.taken_count }}</td>
        {% endcomment %}
        <td class="text-right">
          <a
            href="{% url 'organizers:event_results' event.pk %}"
            class="btn btn-primary"
            >Applicants</a
          >
        </td>
      </tr>
      {% empty %}
      <tr>
        <td class="bg-light text-center font-italic" colspan="5">
          You haven't created any Job yet.
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

Event_Tracker-main/django-schools-master/django_school/classroom/templates/classroom/organizers/event_results.html
{% extends 'base.html' %}

{% load crispy_forms_tags humanize %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'organizers:event_change_list' %}">My Events</a></li>
      <li class="breadcrumb-item"><a href="{% url 'organizers:event_change' event.pk %}">{{ event.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Participants</li>
    </ol>
  </nav>
  <div class="container">
  <div class="row">
    <div class="col-6">
      <h2 class="mb-3">{{ event.name }} Participants</h2>
    </div>
    <div class="col-3">
      <a href="{% url 'organizers:event_attendance' event.pk %}" class="btn btn-success">Mark Attendance</a>
    </div>
    <div class="col-3">
      <a href="{% url 'organizers:event_attendees' event.pk %}" class="btn btn-primary">Event Attendees</a>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <strong>Enrolled Students</strong>
      <span class="badge badge-pill badge-primary float-right">Total Participants: {{ total_enrolled_students|default_if_none:0 }}</span>
    </div>
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Username</th>
          <th>Student</th>
          <th>Date</th>
          {% comment %} <th>Percentage</th> {% endcomment %}
        </tr>
      </thead>
      <tbody>
        {% for enrolled_student in enrolled_students %}
          <tr>
            <td>{{ enrolled_student.student.user.username }}</td>
            <td>{{ enrolled_student.student.user.first_name }}&nbsp{{enrolled_student.student.user.last_name}}</td>
            <td>{{ enrolled_student.date|naturaltime }}</td>
            {% comment %} <td>{{ taken_quiz.percentage }}</td> {% endcomment %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="card-footer text-muted">
      Total Participants: <strong>{{ total_enrolled_students }}</strong>
    </div>
  </div>
{% endblock %}