Event_Tracker-main/django-schools-master/django_school/classroom/urls.py
from django.urls import include, path
from django.conf.urls import url
from .views import classroom, students, organizers

urlpatterns = [
    # url(r"^save_state/$", classroom.save_state, name="save_state"),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("", classroom.home, name="home"),
    path(
        "students/",
        include(
            (
                [
                    path("event/", students.EventListView.as_view(), name="event_list"),
                    # path("s/", students.StudentList.as_view(), name="student_list"),
                    # path(
                    #     "interests/",
                    #     students.StudentInterestsView.as_view(),
                    #     name="student_interests",
                    # ),
                    # path(
                    #     "event/<int:pk>/",
                    #     students.EventDetailView.as_view(),
                    #     name="event-detail",
                    # ),
                    path(
                        "enrolled/",
                        students.EnrolledEventListView.as_view(),
                        name="enrolled_event_list",
                    ),
                    path("enroll/<int:pk>", students.enroll_event, name="enroll_event"),
                    path("event/<int:pk>/", students.event_detail, name="event-detail"),
                    path(
                        "enrolledevent/<int:pk>/",
                        students.enrolled_event_detail,
                        name="enrolled_event_detail",
                    ),
                    path(
                        "enrolledevent/<int:pk>/download",
                        students.download_certi,
                        name="certi",
                    ),
                    path(
                        "enrolledevent/<int:pk>/feedback",
                        students.feedback_form,
                        name="feedback_form",
                    ),
                    path(
                        "enrolledevent/<int:pk>/feedback/save",
                        students.student_feedback,
                        name="feedback",
                    )
                    # path(
                    #     "event/<int:pk>/studentresults/",
                    #     students.EventResultsView.as_view(),
                    #     name="student_event_results",
                    # ),
                ],
                "classroom",
            ),
            namespace="students",
        ),
    ),
    path(
        "organizers/",
        include(
            (
                [
                    path(
                        "", organizers.EventListView.as_view(), name="event_change_list"
                    ),
                    path(
                        "updatedetails/",
                        organizers.DetailsCreateView.as_view(),
                        name="update_details",
                    ),
                    path(
                        "event/add/",
                        organizers.EventCreateView.as_view(),
                        name="event_add",
                    ),
                    path(
                        "event/<int:pk>/",
                        organizers.EventUpdateView.as_view(),
                        name="event_change",
                    ),
                    path(
                        "event/<int:pk>/results/",
                        organizers.EventResultsView.as_view(),
                        name="event_results",
                    ),
                    path(
                        "event/<int:pk>/results/attendance",
                        organizers.EventAttendanceView.as_view(),
                        name="event_attendance",
                    ),
                    path(
                        "event/<int:pk>/results/attendees/",
                        organizers.AttendeesView.as_view(),
                        name="event_attendees",
                    ),
                    path(
                        "event/<int:pk>/results/gen_certi",
                        organizers.generate_certificate,
                        name="generate",
                    ),
                    path(
                        "event/<int:pk>/results/absent_mail",
                        organizers.absent_mail,
                        name="absent_mail",
                    ),
                    # path("savedata/", organizers.savedata, name="save",),
                    path("savedata/<int:pk>", organizers.save_data, name="savedata",),
                    # path(
                    #     "quiz/<int:quiz_pk>/question/<int:question_pk>/",
                    #     teachers.question_change,
                    #     name="question_change",
                    # ),
                    # path(
                    #     "quiz/<int:quiz_pk>/question/<int:question_pk>/delete/",
                    #     teachers.QuestionDeleteView.as_view(),
                    #     name="question_delete",
                    # ),
                ],
                "classroom",
            ),
            namespace="organizers",
        ),
    ),
]

Event_Tracker-main/django-schools-master/django_school/django_school/urls.py
from django.urls import include, path
from django.contrib import admin
from classroom.views import classroom, students, organizers
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("classroom.urls")),
    # path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/signup/", classroom.SignUpView.as_view(), name="signup"),
    path(
        "accounts/signup/student/",
        students.StudentSignUpView.as_view(),
        name="student_signup",
    ),
    path(
        "accounts/signup/organizer/",
        organizers.OrganizerSignUpView.as_view(),
        name="organizer_signup",
    ),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Event_Tracker-main/django-schools-master/django_school/classroom/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from ..decorators import organizer_required
from django.contrib.auth.decorators import login_required


class SignUpView(TemplateView):
    template_name = "registration/signup.html"


def home(request):
    if request.user.is_authenticated:
        if request.user.is_organizer:
            return redirect("organizers:event_change_list")
        elif request.user.is_student:
            return redirect("students:event_list")
        else:
            return redirect("admin:index")
    return render(request, "classroom/home.html")


# @login_required
# @organizer_required
# def save_state(request):
#     if request.method == "POST":
#         title = request.POST.get("student_name", "")
#         checked = request.POST.get("checked", "")
#         print(title)
#         print(checked)
#         # todo = Todo.objects.get(title=title)
#         # todo.completed = checked
#         # todo.save()

Event_Tracker-main/django-schools-master/django_school/classroom/views/organizers.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from PIL import Image, ImageDraw, ImageFont
import os
import io
from django.conf import settings
from django.utils.encoding import smart_str

from django.core.mail import EmailMessage

from django.db import transaction
from django.db.models import Avg, Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render, HttpResponse
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from django.templatetags.static import static
from bootstrap_datepicker_plus import DateTimePickerInput

from ..decorators import organizer_required
from ..forms import (
    OrganizerSignUpForm,
    EventForm,
)
from ..models import Event, Organizer, EnrolledEvents


User = get_user_model()


class OrganizerSignUpView(CreateView):
    model = User
    form_class = OrganizerSignUpForm
    template_name = "registration/signup_form.html"

    def get_context_data(self, **kwargs):
        kwargs["user_type"] = "organizer"
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        messages.success(
            self.request,
            "The account was created Successfully!Please Update your Informtion to get started!",
        )
        return redirect("organizers:update_details")


@method_decorator([login_required, organizer_required], name="dispatch")
class EventListView(ListView):
    model = Event
    ordering = ("name",)
    context_object_name = "events"
    template_name = "classroom/organizers/event_change_list.html"

    def get_queryset(self):
        queryset = self.request.user.events.select_related("organizer")
        return queryset


@method_decorator([login_required, organizer_required], name="dispatch")
class EventCreateView(generic.edit.CreateView):
    model = Event
    form_class = EventForm
    template_name = "classroom/organizers/event_add_form.html"

    def form_valid(self, form):
        event = form.save(commit=False)
        event.owner = self.request.user
        event.save()
        messages.success(self.request, "The event was created with success!Go Ahead!")
        return redirect("organizers:event_change", event.pk)


@method_decorator([login_required, organizer_required], name="dispatch")
class DetailsCreateView(CreateView):
    model = Organizer
    fields = (
        "name",
        "description",
        "email",
        "contact",
        "color",
    )
    template_name = "classroom/organizers/update_details_form.html"

    def form_valid(self, form):
        organizer = form.save(commit=False)
        organizer.save()
        messages.success(self.request, "The Details are Updated Successfully!Go Ahead!")
        return redirect("organizers:event_change_list")


@method_decorator([login_required, organizer_required], name="dispatch")
class EventUpdateView(UpdateView):
    model = Event
    form_class = EventForm
    context_object_name = "event"
    template_name = "classroom/organizers/event_change_form.html"

    def get_context_data(self, **kwargs):
        kwargs["questions"] = self.get_object().questions.annotate(
            answers_count=Count("answers")
        )
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.events.all()

    def get_success_url(self):
        return reverse("organizers:event_change", kwargs={"pk": self.object.pk})


@method_decorator([login_required, organizer_required], name="dispatch")
class EventResultsView(DetailView):
    model = Event
    context_object_name = "event"
    template_name = "classroom/organizers/event_results.html"

    def get_context_data(self, **kwargs):
        event = self.get_object()
        enrolled_students = event.enrolled_events.select_related(
            "student__user"
        ).order_by("-date")
        total_enrolled_students = enrolled_students.count()
        extra_context = {
            "enrolled_students": enrolled_students,
            "total_enrolled_students": total_enrolled_students,
        }
        kwargs.update(extra_context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.events.all()


@method_decorator([login_required, organizer_required], name="dispatch")
class EventAttendanceView(DetailView):
    model = Event
    context_object_name = "event"
    template_name = "classroom/organizers/event_attendance.html"

    def get_context_data(self, **kwargs):
        event = self.get_object()
        enrolled_students = event.enrolled_events.select_related(
            "student__user"
        ).order_by("-date")
        total_enrolled_students = enrolled_students.count()
        extra_context = {
            "enrolled_students": enrolled_students,
            "total_enrolled_students": total_enrolled_students,
        }
        kwargs.update(extra_context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.events.all()


@login_required
@organizer_required
def save_data(request, pk):
    if request.method == "POST":
        # print(request.POST.getlist("present"))
        student_list = request.POST.getlist("present")
        event = Event.objects.get(pk=pk)
        # print(event)

        EnrolledEvents.objects.filter(event=event).filter(
            student__in=student_list
        ).update(present=True)

        EnrolledEvents.objects.filter(event=event).exclude(
            student__in=student_list
        ).update(present=False)
        messages.success(request, "Attendance was Updated Successfully! Go Ahead!")
        return redirect("organizers:event_change_list")


@method_decorator([login_required, organizer_required], name="dispatch")
class AttendeesView(DetailView):
    model = Event
    context_object_name = "event"
    template_name = "classroom/organizers/attendees.html"

    def get_context_data(self, **kwargs):
        event = self.get_object()
        enrolled_students = event.enrolled_events.select_related(
            "student__user"
        ).order_by("-date")
        student_p = EnrolledEvents.objects.filter(event=event, present=True)
        student_a = EnrolledEvents.objects.filter(event=event, present=False)
        attendees_count = student_p.count()
        absentees_count = student_a.count()
        extra_context = {
            "presentees": student_p,
            "absentees": student_a,
            "attendees_count": attendees_count,
            "absentees_count": absentees_count,
        }
        kwargs.update(extra_context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.events.all()


@login_required
@organizer_required
def generate_certificate(request, pk):
    event = Event.objects.get(pk=pk)
    if request.method == "POST":
        enrolled_students = event.enrolled_events.select_related(
            "student__user"
        ).filter(present=True)
        img_url = os.path.join(settings.MEDIA_ROOT, "certi_template.jpg")
        font_path = os.path.join(
            os.path.join(settings.BASE_DIR, "static"), "fonts/Pacifico.ttf"
        )
        font_path1 = os.path.join(
            os.path.join(settings.BASE_DIR, "static"), "fonts/Alexandroupoli.ttf"
        )
        for s in enrolled_students:
            name = s.student.user.first_name + " " + s.student.user.last_name
            text_y_position1 = 550
            text_y_position2 = 780
            text_y_position3 = 950
            img = Image.open(img_url, mode="r")
            image_width = img.width
            image_height = img.height
            draw = ImageDraw.Draw(img)
            date = str(event.dateofEvent)
            font1 = ImageFont.truetype(font_path, 100)
            font2 = ImageFont.truetype(font_path, 70)
            font3 = ImageFont.truetype(font_path, 60)
            font4 = ImageFont.truetype(font_path1, 60)
            text_width1, _ = draw.textsize(name, font=font1)
            text_width2, _ = draw.textsize(event.name, font=font2)
            draw.text(
                ((image_width - text_width1) / 2, text_y_position1,),
                name,
                font=font1,
                fill=(96, 96, 96),
            )
            draw.text(
                ((image_width - text_width2) / 2, text_y_position2,),
                event.name,
                font=font2,
                fill=(96, 96, 96),
            )
            draw.text(
                (1200, text_y_position3,), date, font=font3, fill=(96, 96, 96),
            )
            draw.text(
                (570, text_y_position3,), "Vnrvjiet", font=font4, fill=(96, 96, 96),
            )
            # img.show()
            file_path = os.path.join(settings.MEDIA_ROOT, "gmail_certi/certificate.jpg")
            img.save(file_path)
            student_instance = EnrolledEvents.objects.filter(event=event).filter(
                student=s.student
            )
            student_instance.update(certificate=img.tobytes())
            subject = "Certificate of " + event.name + " from Terrific Trio!"
            message = "Congratulations!!! You have succesfully achieved Certificate from Terrific Trio.Please download it from the website!"
            recepient = s.student.user.email
            msg = EmailMessage(subject, message, settings.EMAIL_HOST_USER, [recepient])
            msg.content_subtype = "html"
            msg.attach_file(file_path)
            msg.send()

        return redirect("organizers:event_change_list")


@login_required
@organizer_required

Event_Tracker-main/django-schools-master/django_school/classroom/templates/classroom/students/_header.html
<h2>Events</h2>


<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <a class="nav-link{% if active == 'new' %} active{% endif %}" href="{% url 'students:event_list' %}">Events</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == 'enrolled' %} active{% endif %}" href="{% url 'students:enrolled_event_list' %}">Enrolled Events</a>
  </li>
  {% comment %} <li class="nav-item">
    <a class="nav-link{% if active == 'students' %} active{% endif %}" href="{% url 'students:student_list' %}">Students</a>
  </li> {% endcomment %}
</ul>

Event_Tracker-main/django-schools-master/django_school/classroom/templates/classroom/students/enrolled_event_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>Title: {{ event.name }}</h1>

  <p><strong>Description:</strong> {{ event.description | safe}}</p>
  <p><strong>Date of Event:</strong> {{ event.dateofEvent }}</p> 
  <p><strong>Registration Fee:</strong> {{ event.registrationFee }}</p>
  <h4>Details of Organizer</h4>
  <p><strong>Name:</strong> {{ organizer.name }}</p>
  <p><strong>Description:</strong> {{ organizer.description }}</p> 
  <p><strong>Email:</strong> {{ organizer.email }}</p>
  <p><strong>Contact:</strong> {{ organizer.contact }}</p>  
{% endblock %}

Event_Tracker-main/django-schools-master/django_school/classroom/templates/classroom/students/enrolled_event_list.html
{% extends 'base.html' %}

{% block content %}
  {% include 'classroom/students/_header.html' with active='enrolled' %}
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Event</th>
          {% comment %} <th>Organizer</th> {% endcomment %}
          <th>Date of Event</th>
        </tr>
      </thead>
      <tbody>
        {% for enrolled_event in enrolled_events %}
          <tr>
            <td><a href = "{% url 'students:enrolled_event_detail' enrolled_event.event.pk %}">{{ enrolled_event.event.name }}</a></td>
            {% comment %} <td>{{ enrolled_event.event.organizer.get_html_badge }}</td> {% endcomment %}
            <td>{{ enrolled_event.event.dateofEvent }}</td>
            <td><a href="{% url 'students:certi' enrolled_event.event.pk %}" {% if enrolled_event.certificate %}class="btn btn-success"{% else %} class="btn btn-success disabled" {% endif %}role="button" aria-disabled="true">Download Certificate</a></td>
            {% if not enrolled_event.feedback %}
            <td><a href = {% url 'students:feedback_form' enrolled_event.event.pk%} class="btn btn-primary">FeedBack</a></td>
            {% endif %}
         </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="3">You haven't enrolled for any event yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

{% endblock %}

Event_Tracker-main/django-schools-master/django_school/classroom/templates/classroom/students/event_detail.html
{% extends 'base.html' %}

{% block content %}


  
  <h1>Title: {{ event.name }}</h1>
  <p><strong>Description:</strong> {{ event.description | safe }}</p>
  <p><strong>Date of Event:</strong> {{ event.dateofEvent }}</p> 
  <p><strong>Registration Fee:</strong> {{ event.registrationFee }}</p>
  <h3>Details of Organizer</h3>
  <p><strong>Name:</strong> {{ organizer.name }}</p>
  <p><strong>Description:</strong> {{ organizer.description }}</p> 
  <p><strong>Email:</strong> {{ organizer.email }}</p>
  <p><strong>Contact:</strong> {{ organizer.contact }}</p>
  <td class="text-right" data-orderable="false">
     {% comment %} <a href="{% url 'students:enroll_event' event.pk%}" class="btn btn-success">Enroll</a> {% endcomment %}
     <a role="button" role="button" class="btn btn-warning nav-link btn-block" id="enrollButton">Enroll</a>
  </td>
  <div id = "enrollModal" class="modal fade" role = "dialog">
        <div class="modal-dialog modal-lg" role="content">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Enrollement Confirmation</h4>
                    <button type="button" class="close" data-dismiss ="modal">
                        &times;
                    </button> 
                </div>
                <div class="modal-body">
                    <div class="col-12 col-md-9">
                      <p>Are you sure you want to register for the Event?<i class="fa fa-handshake-o" aria-hidden="true"></i></p>
                    <div>
                    <div class="form-row">
                        <button type="button" class="btn btn-secondary btn-lg ml-auto" data-dismiss="modal">Cancel</button>
                        <a href="{% url 'students:enroll_event' event.pk%}" class="btn btn-primary btn-lg ml-1">OK</a>        
                    </div>
                </div>
            </div>
        </div>
    </div>  
 
{% endblock %}

{% block js %}
<script>
    $(document).ready(function(){
        $('#enrollButton').click(function() {
            $('#enrollModal').modal('toggle');
        });
    });
  </script>
{% endblock %}

Event_Tracker-main/django-schools-master/django_school/classroom/templates/classroom/students/event_list.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'datatables/dataTables.bootstrap4.min.css' %}">
{% endblock %}

{% block content %}
  {% include 'classroom/students/_header.html' with active='new' %}
  {% comment %} <p class="text-muted">
    Subjects:{% for subject in user.student.interests.all %} {{ subject.get_html_badge }}{% endfor %}
    <a href="{% url 'students:student_interests' %}"><small>(update interests)</small></a>
  </p> {% endcomment %}

  <table class="table table-bordered mb-0" id="tb_eventlist" >
    <thead>
      <tr>
        <th>Event</th>
        <th class="d-none d-sm-table-cell">Organizer</th>
        {% comment %} <th class="d-none d-sm-table-cell">Questions</th> {% endcomment %}
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for event in events %}
        <tr{% if event.organizer.id in student_organizers %} style="background: #fdf7e3"{%endif%}>
          <td class="align-middle">{{ event.name }}</td>
          <td class="align-middle d-none d-sm-table-cell">{{ event.organizer.get_html_badge }}</td>
          {% comment %} <td class="align-middle d-none d-sm-table-cell">{{ quiz.questions_count }}</td> {% endcomment %}
          <td class="text-right" data-orderable="false">
            <a href="{% url 'students:event-detail' event.pk %}" class="btn btn-outline-info">Details</a>
          </td>
        </tr>
      {% empty %}
        <tr>
          <td class="bg-light text-center font-italic" colspan="4">No Events at Present.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

{% block js %}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'datatables/dataTables.bootstrap4.min.js' %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('#tb_eventlist').DataTable({"order": [[ 2, "desc" ]]});
});
</script>
{% endblock %}

Event_Tracker-main/django-schools-master/django_school/classroom/templates/classroom/students/event_result.html
{% extends 'base.html' %}
{% load event_extras %}

{% block content %}
{% include 'classroom/students/_header.html' with active='taken' %}

<h2>{{event.name}}</h2>
{{ event.organizer.get_html_badge }}

{% comment %} <div class="progress">
  <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: {{percentage}}%" aria-valuenow="{{percentage}}" aria-valuemin="0" aria-valuemax="100">{{percentage}}%</div>
</div><br>
{% for question in questions %}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{forloop.counter}}. {{question.text}}</h5>
    <table class="table table-bordered table-sm">
      <thead><tr><th>Yours</th><th>Correct</th><th></th></tr></thead>
      <tbody>
        {% for opt in question.answers.all %}
        {% marked_answer user opt as opt_marked %}        
        <tr>
          <td style="width: 100px;{% if opt_marked == 'correct' %} background:green{% elif opt_marked == 'wrong' %} background:red{% endif %}"> </td>
          <td style="width: 100px;{% if opt.is_correct %} background:green{% endif %}"></td>
          <td>{{opt.text}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div> {% endcomment %}
{% comment %} <br>
{% endfor %} {% endcomment %}
{% endblock %}

Event_Tracker-main/django-schools-master/django_school/classroom/templates/classroom/students/feedback.html
{% extends 'base.html' %}
{% block content%}
<div class="container">
   <div class="row row-content">
           <div class="col-12">
              <h3>Send us your Feedback</h3>
           </div>
    </div>
    <form method="post" action="{% url 'students:feedback' event.pk %}">
        {% csrf_token %}
        <div class="form-group row">
            <div class= "col-md-10">
                <textarea class="form-control" id = "feedback" name = "feedback" rows = "12" > </textarea>
            </div> 
        </div>
        <div class="form-group row">
            <div class=" col-md-10">
                <button type = "submit" class="btn btn-primary">
                    Send Feed Back !
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

Event_Tracker-main/django-schools-master/django_school/classroom/templates/classroom/students/interests_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">Update your interests</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'students:quiz_list' %}" class="btn btn-outline-secondary">Nevermind</a>
  </form>
{% endblock %}